site_name: FedEasy
theme: readthedocs

pages:
  Home: index.md
  Installaton & Setup: install.md
  Confugration: config.md
  Datasets: datasets.md
  Data Distributions: data_distribution.md
  Models : models.md
  Strategies: strategies.md